
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evjfnpzeupppplamdmci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2amZucHpldXBwcHBsYW1kbWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNzY5NDksImV4cCI6MjA1Nzc1Mjk0OX0.dclfRa2HeZb4L1mT-hx-JCYYF2MqWBuAfXhk-QaqC6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
